### ISSUE TITLE
How do we add products & themes?

### ISSUE THREAD

**Issue by davidascher** [darrinhenein/cupcake-dashboard#14]
what’s the process to add products to the dashboard?  is there a ui i didn’t see, or is it asking you?

I think we should add Webmaker and Appmaker at least. =)

Same question about Themes.  And the q as to whether themes are product specific, or not.

**Comment by darrinhenein** [comment]
Currently, its a bit buried. At the bottom of the /products or /themes pages, you should see a New Product/Theme button when logged in. Needs better UX, but closing this for now.

Themes and Products are orthogonal, so no dependecy between. Themes aim to group projects which may be cross-product (i.e. Save for Later) and Products let functional teams view their scoped ideas.
