### ISSUE TITLE
remove dependencies

### ISSUE THREAD

**Issue by davidascher** [darrinhenein/cupcake-dashboard#27]
no matter what @bwinton says, they currently break stuff.

node_modules in main and app/, and bower_components, IMO, can go.

**Comment by bwinton** [comment]
Not just me, but also [people](http://www.futurealoof.com/posts/nodemodules-in-git.html) who have worked far more [with node](https://www.npmjs.org/doc/faq.html#Should-I-check-my-node_modules-folder-into-git) than I have.

What do they break?  Perhaps that would be worth fixing, or letting other people know about…

**Comment by darrinhenein** [comment]
It seemed like in this case, despite what git was telling me, some files from bower_components were not getting added to the repo. Probably going to delete the deps from the repo for sanity's sake right now.

**Comment by davidascher** [comment]
agree that there's likely a bug somewhere.  the fact that it's to do w/
bower_components suggest to me that that's where the issue is.

i'm just glad it's working for me now =)

**Comment by davidascher** [comment]
oh, and i admit that mikeal might be right on this stuff, but the fact is
those checked in modules did cause me pain, so there ;-)

**Comment by darrinhenein** [comment]
Done.
https://github.com/darrinhenein/cupcake-dashboard/commit/31ab24f7d029c1e0c3f8340206e487dccbb4f196
