### ISSUE TITLE
Error running "grunt build" with "Object Gruntfile.js has no method 'flatten'"

### ISSUE THREAD

**Issue by toolness** [darrinhenein/cupcake-dashboard#35]
Looking at https://github.com/gruntjs/grunt/issues/888, it seems like this might have something to do with `dist` being in `app/.gitignore`? I'm new to grunt, so not really sure...

**Comment by darrinhenein** [comment]
This is related to https://github.com/darrinhenein/cupcake-dashboard/issues/21 and https://github.com/darrinhenein/cupcake-dashboard/issues/27, the quick fix until I push a commit is to remove your app/app/bower_components folder completely, then run `bower install` in /app.

**Comment by toolness** [comment]
Is `grunt build` supposed to work after that? Because it's still giving me the same error...

**Comment by toolness** [comment]
Oh, it looks like `npm cache clean` magically fixed things!
