### ISSUE TITLE
Provide and document a JSON API for the data in the dashboard

### ISSUE THREAD

**Issue by davidascher** [darrinhenein/cupcake-dashboard#9]
Specifically, I'd like a search API that would let me find all of the status data about proposals matching a set of constraints (tags, search for string in product names, …).  The JSON result would ideally have enough data to populate something kinda like the overviwe pages on the dashboard.  I'm happy to do another JSON call to get the deep data on the details of a cupcake.

/cc @simonwex

**Comment by davidascher** [comment]
I should motivate this request.  We're going to be doing a bunch of prototyping work as part of this project http://mozilla.github.io/mobile-opportunity/, and I'd love to use cupcake to both track the prototype evolution and record the feedback/etc..  I also want to be able to display high level summaries of those prototypes on that site, without having to maintain the state about each prototype in two places.  I'm happy to do the rendering on that site off of JSON data that I pull out of cupcake.

Let me know if the request makes sense. [also happy to contribute a PR once I figure out the code a bit]

**Comment by davidascher** [comment]
Wow look at that: https://cupcake-dashboard.paas.allizom.org/api/projects/

I think that will do for now.

**Comment by darrinhenein** [comment]
Hey David! Thanks for the interest in the dashboard :) I'm going to spend some time cleaning up the code a bit, it was built a bit hastily and could use some organization. I won't break the API if possible, but rather just get the server codebase to a better state. Thanks for filing all these issues :)

**Comment by davidascher** [comment]
Doesn't matter if you break the api.  go forth and refactor, I can adapt to changes.

**Comment by darrinhenein** [comment]
PS re: APIs, the entire app is built in Angular against an Express/Node driven API. I just pushed an update which exploes the existing endpoints, available at `/api` (https://cupcake-dashboard.paas.allizom.org/api).

**Comment by davidascher** [comment]
sweet. add to the README?
